### ISSUE TITLE
Secure connection not establish on mac os

### ISSUE THREAD

**Issue by bim13** [jchambers/pushy#770] opened 2020-04-22 10:23 UTC
I have problems on Mac OS 10.15.4. Problem not reproduced on Linux.
Java version: 1.8.0_231
I am using pushy version: '0.13.10'
When I am trying to send notification:
```
final PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>> sendNotificationFuture = service.sendNotification(pushNotification);
        sendNotificationFuture.addListener( listener );
```

I recieve warning:

```2020-04-22 12:57:37,095 [nioEventLoopGroup-2-1] WARN  - An exception was thrown by my.package.myClass$$Lambda$119/1767425990.operationComplete()
java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: state
	at io.netty.util.concurrent.DefaultPromise.get(DefaultPromise.java:349)
	at my.package.myClass$initListener$0(MyClass.java:112)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at com.turo.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:226)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at com.turo.pushy.apns.ApnsChannelPool$3.operationComplete(ApnsChannelPool.java:169)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at com.turo.pushy.apns.ApnsChannelFactory.tryFailureAndLogRejectedCause(ApnsChannelFactory.java:267)
	at com.turo.pushy.apns.ApnsChannelFactory.access$100(ApnsChannelFactory.java:58)
	at com.turo.pushy.apns.ApnsChannelFactory$1$1.operationComplete(ApnsChannelFactory.java:163)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.handler.ssl.SslHandler.handleUnwrapThrowable(SslHandler.java:1251)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1233)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchFieldError: state
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:198)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:970)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:967)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1475)
	at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1502)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1516)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1400)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1227)
	... 20 more

2020-04-22 12:57:37,103 [nioEventLoopGroup-2-1] WARN  - Tried to mark promise as "failed," but it was already done.
java.lang.NoSuchFieldError: state
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:198)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:970)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:967)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1475)
	at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1502)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1516)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1400)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1227)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
full network log:
```
2020-04-22 12:57:34,029 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.processId: 14023 (auto-detected)
2020-04-22 12:57:34,032 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.machineId: ac:bc:32:ff:fe:a6:a9:ad (auto-detected)
2020-04-22 12:57:34,045 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.leakDetection.level: advanced
2020-04-22 12:57:34,045 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.leakDetection.targetRecords: 4
2020-04-22 12:57:34,072 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.allocator.numHeapArenas: 5
2020-04-22 12:57:34,072 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.allocator.numDirectArenas: 5
2020-04-22 12:57:34,072 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.allocator.pageSize: 8192
2020-04-22 12:57:34,072 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.allocator.maxOrder: 11
2020-04-22 12:57:34,072 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.allocator.chunkSize: 16777216
2020-04-22 12:57:34,072 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.allocator.tinyCacheSize: 512
2020-04-22 12:57:34,072 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.allocator.smallCacheSize: 256
2020-04-22 12:57:34,072 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.allocator.normalCacheSize: 64
2020-04-22 12:57:34,072 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
2020-04-22 12:57:34,072 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.allocator.cacheTrimInterval: 8192
2020-04-22 12:57:34,072 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
2020-04-22 12:57:34,072 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.allocator.useCacheForAllThreads: true
2020-04-22 12:57:34,072 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
2020-04-22 12:57:34,080 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.allocator.type: pooled
2020-04-22 12:57:34,080 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.threadLocalDirectBufferSize: 0
2020-04-22 12:57:34,080 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.maxThreadLocalCharBufferSize: 16384
Using SSLEngineImpl.
2020-04-22 12:57:34,133 [nioEventLoopGroup-2-1] DEBUG - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@62ee2e69
2020-04-22 12:57:34,144 [nioEventLoopGroup-2-1] DEBUG - [id: 0x97c39b4a] WRITE: UDP, [33931: /217.150.34.129:53], DefaultDnsQuestion(api.development.push.apple.com. IN A)
2020-04-22 12:57:34,150 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.recycler.maxCapacityPerThread: 4096
2020-04-22 12:57:34,150 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.recycler.maxSharedCapacityFactor: 2
2020-04-22 12:57:34,151 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.recycler.linkCapacity: 16
2020-04-22 12:57:34,151 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.recycler.ratio: 8
2020-04-22 12:57:34,158 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.buffer.checkAccessible: true
2020-04-22 12:57:34,158 [nioEventLoopGroup-2-1] DEBUG - -Dio.netty.buffer.checkBounds: true
2020-04-22 12:57:34,158 [nioEventLoopGroup-2-1] DEBUG - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@65e30470
2020-04-22 12:57:34,167 [nioEventLoopGroup-2-1] DEBUG - [id: 0x97c39b4a] WRITE: UDP, [56336: /217.150.34.129:53], DefaultDnsQuestion(api.development.push.apple.com. IN AAAA)
2020-04-22 12:57:34,294 [nioEventLoopGroup-2-1] DEBUG - [id: 0x97c39b4a] RECEIVED: UDP [33931: /217.150.34.129:53], DatagramDnsResponse(from: /217.150.34.129:53, to: /0:0:0:0:0:0:0:0:50178, 33931, QUERY(0), NoError(0), RD RA)
	DefaultDnsQuestion(api.development.push.apple.com. IN A)
	DefaultDnsRawRecord(api.development.push.apple.com. 300 IN CNAME 39B)
	DefaultDnsRawRecord(api.sandbox.push-apple.com.akadns.net. 10 IN A 4B)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
2020-04-22 12:57:34,296 [nioEventLoopGroup-2-1] DEBUG - [id: 0x97c39b4a] WRITE: UDP, [28911: /217.150.34.129:53], DefaultDnsQuestion(api.sandbox.push-apple.com.akadns.net. IN A)
2020-04-22 12:57:34,303 [nioEventLoopGroup-2-1] DEBUG - [id: 0x97c39b4a] RECEIVED: UDP [28911: /217.150.34.129:53], DatagramDnsResponse(from: /217.150.34.129:53, to: /0:0:0:0:0:0:0:0:50178, 28911, QUERY(0), NoError(0), RD RA)
	DefaultDnsQuestion(api.sandbox.push-apple.com.akadns.net. IN A)
	DefaultDnsRawRecord(api.sandbox.push-apple.com.akadns.net. 10 IN A 4B)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
2020-04-22 12:57:34,323 [nioEventLoopGroup-2-1] DEBUG - [id: 0x97c39b4a] RECEIVED: UDP [56336: /217.150.34.129:53], DatagramDnsResponse(from: /217.150.34.129:53, to: /0:0:0:0:0:0:0:0:50178, 56336, QUERY(0), NoError(0), RD RA)
	DefaultDnsQuestion(api.development.push.apple.com. IN AAAA)
	DefaultDnsRawRecord(api.development.push.apple.com. 300 IN CNAME 39B)
	DefaultDnsRawRecord(akadns.net. 180 IN SOA 51B)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
2020-04-22 12:57:34,324 [nioEventLoopGroup-2-1] DEBUG - [id: 0x97c39b4a] WRITE: UDP, [55689: /217.150.34.129:53], DefaultDnsQuestion(api.sandbox.push-apple.com.akadns.net. IN AAAA)
2020-04-22 12:57:34,330 [nioEventLoopGroup-2-1] DEBUG - [id: 0x97c39b4a] RECEIVED: UDP [55689: /217.150.34.129:53], DatagramDnsResponse(from: /217.150.34.129:53, to: /0:0:0:0:0:0:0:0:50178, 55689, QUERY(0), NoError(0), RD RA)
	DefaultDnsQuestion(api.sandbox.push-apple.com.akadns.net. IN AAAA)
	DefaultDnsRawRecord(akadns.net. 180 IN SOA 54B)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 for TLSv1
No available cipher suite for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 for TLSv1.1
No available cipher suite for TLSv1.1
%% No cached client session
update handshake state: client_hello[1]
upcoming handshake states: server_hello[2]
*** ClientHello, TLSv1.2
RandomCookie:  GMT: 1570772239 bytes = { 234, 117, 181, 2, 241, 168, 138, 189, 49, 194, 224, 190, 87, 134, 106, 253, 252, 236, 61, 110, 220, 153, 64, 2, 54, 216, 35, 30 }
Session ID:  {}
Cipher Suites: [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]
Compression Methods:  { 0 }
Extension elliptic_curves, curve names: {secp256r1, secp384r1, secp521r1}
Extension ec_point_formats, formats: [uncompressed]
Extension signature_algorithms, signature_algorithms: SHA512withECDSA, SHA512withRSA, SHA384withECDSA, SHA384withRSA, SHA256withECDSA, SHA256withRSA, SHA256withDSA, SHA224withECDSA, SHA224withRSA, SHA224withDSA, SHA1withECDSA, SHA1withRSA, SHA1withDSA
Extension extended_master_secret
Extension renegotiation_info, renegotiated_connection: <empty>
***
[write] MD5 and SHA1 hashes:  len = 112
0000: 01 00 00 6C 03 03 5E A0   15 0F EA 75 B5 02 F1 A8  ...l..^....u....
0010: 8A BD 31 C2 E0 BE 57 86   6A FD FC EC 3D 6E DC 99  ..1...W.j...=n..
0020: 40 02 36 D8 23 1E 00 00   08 C0 2C C0 30 C0 2B C0  @.6.#.....,.0.+.
0030: 2F 01 00 00 3B 00 0A 00   08 00 06 00 17 00 18 00  /...;...........
0040: 19 00 0B 00 02 01 00 00   0D 00 1C 00 1A 06 03 06  ................
0050: 01 05 03 05 01 04 03 04   01 04 02 03 03 03 01 03  ................
0060: 02 02 03 02 01 02 02 00   17 00 00 FF 01 00 01 00  ................
nioEventLoopGroup-2-1, WRITE: TLSv1.2 Handshake, length = 112
[Raw write]: length = 117
0000: 16 03 03 00 70 01 00 00   6C 03 03 5E A0 15 0F EA  ....p...l..^....
0010: 75 B5 02 F1 A8 8A BD 31   C2 E0 BE 57 86 6A FD FC  u......1...W.j..
0020: EC 3D 6E DC 99 40 02 36   D8 23 1E 00 00 08 C0 2C  .=n..@.6.#.....,
0030: C0 30 C0 2B C0 2F 01 00   00 3B 00 0A 00 08 00 06  .0.+./...;......
0040: 00 17 00 18 00 19 00 0B   00 02 01 00 00 0D 00 1C  ................
0050: 00 1A 06 03 06 01 05 03   05 01 04 03 04 01 04 02  ................
0060: 03 03 03 01 03 02 02 03   02 01 02 02 00 17 00 00  ................
0070: FF 01 00 01 00                                     .....
[Raw read]: length = 5
0000: 16 03 03 00 5B                                     ....[
[Raw read]: length = 91
0000: 02 00 00 57 03 03 5E A0   15 0F E5 74 54 77 6A 42  ...W..^....tTwjB
0010: D3 FB 99 B6 4F 29 B7 47   93 4C D9 08 19 FA 10 CB  ....O).G.L......
0020: 86 52 71 D5 E6 3A 20 F2   48 65 D9 C7 17 06 A8 64  .Rq..: .He.....d
0030: 13 38 B2 82 F7 36 83 6F   CF 45 44 DD A4 42 05 18  .8...6.o.ED..B..
0040: 87 50 87 75 CA 61 BE C0   30 00 00 0F 00 17 00 00  .P.u.a..0.......
0050: FF 01 00 01 00 00 0B 00   02 01 00                 ...........
nioEventLoopGroup-2-1, READ: TLSv1.2 Handshake, length = 91
nioEventLoopGroup-2-1, called closeOutbound()
nioEventLoopGroup-2-1, closeOutboundInternal()
nioEventLoopGroup-2-1, SEND TLSv1.2 ALERT:  warning, description = close_notify
nioEventLoopGroup-2-1, WRITE: TLSv1.2 Alert, length = 2
nioEventLoopGroup-2-1, called closeInbound()
nioEventLoopGroup-2-1, fatal error: 80: Inbound closed before receiving peer's close_notify: possible truncation attack?
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
nioEventLoopGroup-2-1, SEND TLSv1.2 ALERT:  fatal, description = internal_error
nioEventLoopGroup-2-1, Exception sending alert: java.io.IOException: writer side was already closed.
nioEventLoopGroup-2-1, called closeOutbound()
nioEventLoopGroup-2-1, closeOutboundInternal()
[Raw write]: length = 7
0000: 15 03 03 00 02 01 00                               .......
```
What I'am doing wrong?

**Comment by bim13** [comment] 2020-04-22 11:41
problem was solved by changing `forceNpn` property jetty-alpn-agent from `false` to `true`
`-javaagent:./lib/jetty-alpn-agent-2.0.10.jar=forceNpn=true`

**Comment by jchambers** [comment] 2020-04-25 16:00
Okay; sounds like the problem is resolved. We generally do _not_ recommend using the ALPN agent any more (Pushy now does prior-knowledge connections and does not do ALPN), and so removing the agent entirely may also solve your problem.

That said, it sounds like we can close this issue. Please let me know if I'm mistaken.

**Closed by jchambers** 2020-04-25 16:00 UTC
