### ISSUE TITLE
"TooManyProviderTokenUpdates"  received when sent a push notification to apns using .p8

### ISSUE THREAD

**Issue by JackZhangOnly** [jchambers/pushy#568] opened 2017-12-19 09:37 UTC
I was using the pushy library.

"TooManyProviderTokenUpdates"  received when sent a push notification to apns using .p8 file.

[https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1]
This document indicates that "TooManyProviderTokenUpdates" means The provider token is being updated too often.

But i am still confused,What does that mean ?
The provider token is being updated by what ?

What's right solution? Any reply is appreciated,Thanks very much.

**Comment by jchambers** [comment] 2017-12-23 14:36
The "provider token" is the authentication token derived from your private key (the one in the `.p8` file). Tokens expire after an hour, and so they need to be regenerated. `TooManyProviderTokenUpdates` indicates this is happening more often than expected.

You're the first person to report this problem, and so I suspect it is not a widespread bug. Can you please share more information about your setup and your approach to sending push notifications? My suspicion is that you are, for example, creating a new `ApnsClient` for each push notification, or have set an extremely high concurrency level.

**Comment by jchambers** [comment] 2018-01-05 16:59
Closing due to lack of information. @JackZhangOnly please leave a comment if you have any additional information and we'll happily reopen this issue.

**Comment by hjhstanley** [comment] 2018-11-21 08:09
i met the same problem. my implementation updates the provider token every 50 minutes, and there are two process running, so it will trigger twice every 50 minutes. and then i get 429 carrying TooManyProviderTokenUpdates every few days

**Comment by hjhstanley** [comment] 2018-11-21 08:10
@jchambers

**Comment by jchambers** [comment] 2018-11-21 15:01
> my implementation updates the provider token every 50 minutes

I'm confused; Pushy doesn't make that behavior configurable. Can you say more about what you're doing to update the provider token?

Also, as a general note, you do not need to tag me directly on issues or pull requests.

**Comment by hjhstanley** [comment] 2018-11-22 01:35
> > my implementation updates the provider token every 50 minutes
> 
> I'm confused; Pushy doesn't make that behavior configurable. Can you say more about what you're doing to update the provider token?
> 
> Also, as a general note, you do not need to tag me directly on issues or pull requests.

thank you for your help and i'm sorry for tagging you.

and what we're doing is :  there are several servers in which there are several process running the push application, using .p8 based authentication. Each process maintains one connection with APNS. Each process maintains  respective jwt token, and rotates it every 50 minutes.

**Comment by jchambers** [comment] 2018-11-22 01:40
> Each process maintains respective jwt token, and rotates it every 50 minutes.

Right; I think this is the part where we're not on the same page. How do you tell each process to rotate its tokens every 50 minutes?

**Comment by hjhstanley** [comment] 2018-11-22 02:13
> > Each process maintains respective jwt token, and rotates it every 50 minutes.
> 
> Right; I think this is the part where we're not on the same page. How do you tell each process to rotate its tokens every 50 minutes?

there is timer in each process， when 50 minute reaches, each process rotate it's token, respectively.

**Comment by hjhstanley** [comment] 2018-11-22 02:46
pardon me. i finally realize that this is the pushy page, and i didn't use the library...
sorry for my disturbance.

**Comment by jchambers** [comment] 2020-06-04 01:36
Okay—now _I've_ seen this in the real world, so I'm convinced it's A Thing. We saw a flurry of `TooManyProviderTokenUpdates` followed by a long run of "token has expired." I'll dig in.

**Closed** 2020-06-04 12:23 UTC

**Comment by kicktipp** [comment] 2022-01-03 10:26
Is this really fixed? We use pushy 0.15.0 and are getting lots of errors of this type.
We use pushy in our cluster of 20 application servers. I would expect to happen after restart of the cluster when 20 clients connect. But this is not the case. There can't discover any pattern yet. 

This error occurs since updating from 0.14.2

**Comment by jchambers** [comment] 2022-01-03 15:39
@kicktipp Let's move this discussion to #931, which is both open and more specifically about Pushy 0.15. That said, I'll have the [same question](https://github.com/jchambers/pushy/issues/931#issuecomment-994212696) for you as the original poster: can you please share debug logs so we can figure out what's going on here?

**Comment by kicktipp** [comment] 2022-01-11 09:59
I added a log config to get the logging you asked for. Stay tuned for this. 

As far as I can tell, the reason might be our clustered configuration. We run 20+ application server, each is sending apns notifications with the same authentication token. The error message on one server might be caused by an authentication token update of another server inside the cluster. 

The documentation does not say anything about this, see here "Refresh Your Token Regularly"
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns

But other people are asking this question, too:
https://developer.apple.com/forums/thread/675879
