### ISSUE TITLE
Future callback is not called after sending notification

### ISSUE THREAD

**Issue by cyflhn** [jchambers/pushy#923] opened 2021-11-01 06:42 UTC
Here is my code of sending notifications:
```
            PushNotificationFuture<ApnsPushNotification, PushNotificationResponse<ApnsPushNotification>> sendFuture = client.sendNotification(message);
            sendFuture.whenComplete((response, cause) -> {
                xxxxxxx
            });
```
I found that sometimes the callback of `sendFuture` is not called. Is there any method to trace this problem? What is the possible reason for this issue.

**Comment by wtopps** [comment] 2021-11-01 10:21
I found the same problem, waiting for the solution.

**Comment by jchambers** [comment] 2021-11-01 18:44
Can you please provide some more information? In particular:

1. What version of Pushy are you using?
2. When did this problem start?
3. Did anything change (a new version of Pushy? new patterns in notification-sending behavior on your end?) around the time this started happening?
4. How often does this happen? Every notification? 1 in 10? 1 in 1,000,000?
5. When this happens, do notifications you send _after_ the "stuck" notification have their futures completed?

Let's start there. Depending on the answers, it may make sense to add a [frame logger](https://pushy-apns.org/apidocs/latest/com/eatthepath/pushy/apns/ApnsClientBuilder.html#setFrameLogger(io.netty.handler.codec.http2.Http2FrameLogger)) so we can figure out what's going on, but let's take things one step at a time for now.

**Comment by wtopps** [comment] 2021-11-02 02:36
hi, my error log is here:
```
java.net.ConnectException: Operation timed out
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

I use pushy in version 0.14.2，I don not upgrade version recently 6 month. 

When the error happened, the push operate is "stuck", it can not send notification, and there is not error log again.

Please help us to check what problem happened, thank you bro.

**Comment by cyflhn** [comment] 2021-11-02 02:36
@jchambers 
1. The current version of Pushy is 0.14.3-SNAPSHOT
2. We are not quite sure about when did this problem start.  Maybe since we upgraded the Pusy version from 0.13.12 to the current version.
3. We changed the version of Pushy
4. This issue does not happen frequently, but once it occurs, all subsequent callback of `sendFuture ` for notifications won't be called.

**Comment by jchambers** [comment] 2021-11-02 14:21
Could you please try updating to Pushy 0.15.0 and seeing if the problem persists?

**Comment by cyflhn** [comment] 2021-11-02 23:11
@jchambers Sure, I can upgrade Pushy to the lastest version, but I hope that I can get the reason of this issue. If this issue still exists in latest version. our team will be under greate pressure.

**Comment by jchambers** [comment] 2021-11-03 00:46
Pushy 0.15 includes a number of bug fixes. Updating will help us understand if one of them is at play here. As I mentioned earlier, if you're still having this problem after updating, we'll move on to collecting frame logs to better understand what's happening.

**Comment by cyflhn** [comment] 2021-11-03 00:54
@jchambers it is a little bit hard for us to collect frame logs as we have huge number of notifications each day, we cannot turn on debug log.

**Comment by wtopps** [comment] 2021-11-09 01:56
@jchambers 
hi, bro, I upgrade the version to 0.15, the "stuck" problem is gone. But the application in version "0.14.x", it is still occur "stuck" problem.

**Comment by jchambers** [comment] 2021-11-09 02:28
Okay; great. Since it sounds like this is fixed in 0.15, it sounds like the issue is resolved. Is that fair, or am I misunderstanding the situation?

@cyflhn Has updating to Pushy 0.15 fixed the problem for you, too?

**Comment by cyflhn** [comment] 2021-11-09 22:14
@jchambers I will try it

**Comment by jchambers** [comment] 2021-11-28 23:07
At this point, we have one confirmation that updating to the latest version of Pushy solves this problem, and to the best of my knowledge, no ongoing complaints. I'm going to go ahead and close this issue. @cyflhn if you are, indeed, still having problems, please post a comment here and I'll happily re-open the issue.

**Closed by jchambers** 2021-11-28 23:07 UTC
