### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by pgus2024** [jchambers/pushy#1063] opened 2024-05-14 15:01 UTC
We are getting the following exception with Pushy 0.15.4 and netty-tcnative-boringssl-static 2.0.62.Final

`loglevel=ERROR logger=io.netty.util.ResourceLeakDetector LEAK: ReferenceCountedOpenSslContext.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:261)
	io.netty.handler.ssl.ReferenceCountedOpenSslClientContext.<init>(ReferenceCountedOpenSslClientContext.java:68)
	io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:843)
	io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:615)
	com.eatthepath.pushy.apns.ApnsClientBuilder.build(ApnsClientBuilder.java:619)`

Context: We operate several applications that utilize a shared platform for delivering notifications. Currently, we store instances of ApnsClient to the certificate information, in a Google cache with an expiry set to one hour. Are there any adjustments we should consider making to address this issue?

**Comment by jchambers** [comment] 2024-05-17 01:49
The problem is almost certainly that you are not calling `ApnsClient#close()` when clients get evicted from your cache.

To quote the [`ApnsClient` documentation](https://pushy-apns.org/apidocs/latest/com/eatthepath/pushy/apns/ApnsClient.html):

> APNs clients are intended to be long-lived, persistent resources. They are also inherently thread-safe and can be shared across many threads in a complex application. Callers must shut them down via the [close()](https://pushy-apns.org/apidocs/latest/com/eatthepath/pushy/apns/ApnsClient.html#close()) method when they are no longer needed (i.e. when shutting down the entire application). If an event loop group was specified at construction time, callers should shut down that event loop group when all clients using that group have been disconnected.

I am not deeply familiar with Guava caches (which is what I presume you mean by "Google cache"), but it sounds like you may need a [removal listener](https://github.com/google/guava/wiki/CachesExplained#removal-listeners).

I am confident there is not a bug here, and so will close this issue.

**Closed by jchambers** 2024-05-17 01:49 UTC
