### ISSUE TITLE
operationComplete not being called 

### ISSUE THREAD

**Issue by robertoprato** [jchambers/pushy#787] opened 2020-06-09 15:23 UTC
We are seeing an issue when trying to send about 1Million pushes. After 500K / 600K pushes sent the ApnsResponseListener.operationComplete stops being called.
Restarting the server will fix the issue and sending restarts. 

I have a SpringBoot application using Pushy Version 0.13.10.
There is a RabbitMQ queue of messages and 20 threads consuming those messages in parallel.
Each message is passed to an instance of a  Sender class that holds a long lived instance of the ApnsClient class.

The Sender class implements a flow control with a Semaphore initialised with 35000 permits.

```
class Sender {

	Semaphore semaphore = new Semaphore(35000);

	public void sendPush(notification) {
		 semaphore.acquire(1);	 
		 response = apnsClient.sendNotification(notification);
		 response.addListener(new ApnsResponseListener(semaphore));
		}
}
```

On Sending the notification we add a listener to the future to process the result asynchronously.
Inside the operationComplete we then release the semaphore permit.

The listener class is something like the below snippet: 

```
class ApnsResponseListener implements GenericFutureListener<Future<PushNotificationResponse<SimpleApnsPushNotification>>>  {

 Semaphore semaphore;
 
 ApnsResponseListener(Semaphore semaphore) {
  this.semaphore = semaphore;
 }

 @Override
  void operationComplete(Future<PushNotificationResponse<SimpleApnsPushNotification>> future) throws Exception {
	semaphore.release(); 
  }
}
```

**Comment by jchambers** [comment] 2020-06-11 19:22
Pushy 0.13.10 is a couple releases old now, and there have been significant improvements since then. Could you please try with the current version and see if you can still reproduce the problem?

**Comment by robertoprato** [comment] 2020-06-15 10:07
Thanks @jchambers for getting back to me. 
Looking at the comments on https://github.com/jchambers/pushy/pull/747 I think we might be incurring into the same issue of expiring tokens. 
We will do first an upgrade to 0.13.2 to see if the fix in this PR https://github.com/jchambers/pushy/pull/747 resolves the problem. 

Regards,
Roberto

**Comment by jchambers** [comment] 2020-07-18 14:46
@robertoprato Is this still an issue for you, or did an update to a recent version of Pushy sort things out?

**Comment by robertoprato** [comment] 2020-07-21 09:31
Hi @jchambers  we first did an update to 0.13.2 and with this version we are still experiencing the issue. 
We have now updated to Pushy 0.14.1 and will release it to production in the next couple of weeks and will test again  and drop an update here when I have the results.

**Comment by jchambers** [comment] 2020-08-23 17:20
I'm going to close this issue for now because we don't have enough information to take meaningful action. @robertoprato if you get a chance to post the follow-up results, I'll happily reopen this issue. Thanks!

**Closed by jchambers** 2020-08-23 17:20 UTC
