### ISSUE TITLE
Maybe memory leak in pushy-0.14.2

### ISSUE THREAD

**Issue by linzx0403** [jchambers/pushy#867] opened 2021-03-25 14:37 UTC
I use pushy-0.14.2 in product environment, and it is a large number of push notify everyday.  Run for a period of time,  frequently full gc  from the application. Then i dump the jvm memory, and found _com.eatthepath.pushy.apns.ApnsChannelPool#pendingAcquisitionPromises_ uses a lot of memory. The results of the analysis  by MAT like this:

Class Name | Shallow Heap | Retained Heap
-- | -- | --
java.lang.Object[2097152] @ 0x792655e40 | 8,388,624 | 2,004,385,800
elements java.util.ArrayDeque @ 0x728af7b50 | 24 | 2,004,385,824
pendingAcquisitionPromises com.eatthepath.pushy.apns.ApnsChannelPool @ 0x7287d5380 | 48 | 2,004,430,384
channelPool com.eatthepath.pushy.apns.ApnsClient @ 0x7292e4570 | 40 | 2,004,430,480
apnsClient com.xxx.push.xxx.push.apns.IOSClient @ 0x7287d5350 | 48 | 2,004,430,712
iosClient com.xxx.push.xxx.push.apns.IOSPushHandler @ 0x7292e4548 | 40 | 2,004,440,352
<Java Local> java.lang.Thread @ 0x728f9c9e0  pool-56-thread-3 Thread | 120 | 20,880

The com.eatthepath.pushy.apns.ApnsClient keeps long-live during application running, and I use follow-up to get result
```
sendNotificationFuture.whenComplete((response, cause) -> {
    if (response != null) {
        // Handle the push notification response as before from here.
    } else {
        // Something went wrong when trying to send the notification to the
        // APNs server. Note that this is distinct from a rejection from
        // the server, and indicates that something went wrong when actually
        // sending the notification or waiting for a reply.
        cause.printStackTrace();
    }
});
```

And the concurrentConnections sets less then 10. Is it a bug, or how should i to fix this problem?

**Comment by jchambers** [comment] 2021-03-29 14:12
A few clarifying questions:

- How many promises are in memory?
- Am I correct in understanding that the main problem is that you're seeing frequent full GC runs, but that the memory is correctly reclaimed after a run?
- Have you seen any signs that connection attempts are slow or failing with any frequency?

Thanks!

**Comment by jchambers** [comment] 2021-03-31 21:05
I strongly suspect this is a duplicate of #854/#857. Barring more information in the next couple days, I'll mark this as closed, too.

**Comment by jchambers** [comment] 2021-04-20 12:59
As mentioned earlier, I suspect this is a duplicate and we have not received any additional information about this issue. I'll close this for now; please leave a comment if you feel this is a mistake.

**Closed by jchambers** 2021-04-20 12:59 UTC
