### ISSUE TITLE
No APNS status code when I received GOAWAY?

### ISSUE THREAD

**Issue by SK-Yang** [jchambers/pushy#878] opened 2021-04-09 06:12 UTC
Pushy 0.14.2

I read the APNS development doc, they say they will provide status code when they give the GOAWAY command. But when I turn on the Debug log, I don't see any of that. Does that mean APNS provided nothing but just kicked me out?

```
[DEBUG] 2021-03-25 12:16:24.206 [nioEventLoopGroup-2-1] ApnsClientHandler - Received settings from APNs gateway: {=4096, =1000, =65535, =16384, =8000}
[DEBUG] 2021-03-25 12:16:24.237 [nioEventLoopGroup-2-1] Http2ConnectionHandler - [id: 0x689c9907, L:/192.168.0.97:54313 - R:api.push.apple.com/17.188.182.78:443] Sent GOAWAY: lastStreamId '2147483647', errorCode '2', debugData ''. Forcing shutdown of the connection.
[DEBUG] 2021-03-25 12:16:24.237 [WebContainer : 0] Log4j - [ZA1Rdw0R-Iq8lKgdBAWBti6] APNS push error: java.io.IOException: Stream closed before a reply was received
```

**Comment by jchambers** [comment] 2021-04-09 17:39
This appears to be a duplicate of #865, and was fixed in #874. #874 will go out as part of the Pushy 0.15 release.

**Closed by jchambers** 2021-04-09 17:39 UTC
