### ISSUE TITLE
Don't use static exception objects

### ISSUE THREAD

**Issue by lkesteloot** [jchambers/pushy#807] opened 2020-09-15 18:38 UTC
In `ApnsClientHandler.java` this static exception is defined:

```
private static final IOException STREAM_CLOSED_BEFORE_REPLY_EXCEPTION =
            new IOException("Stream closed before a reply was received");
```

and used three times. This makes it impossible to know where the problem actually occurred, since the stack trace does not include the location of the problem. Can you create a new exception object each time, so that the stack trace can be captured and logged?

**Comment by jchambers** [comment] 2020-09-17 00:06
This is a deliberate decision to avoid spending time populating stack traces with the rationale that the same problem could occur at multiple stages of the pipeline. Can you elaborate on the use case for knowing precisely where in the pipeline the stream was closed?

**Comment by dcollens** [comment] 2020-09-17 02:27
Hi Jon, I work with Lawrence. Let me explain how we got to this point.

We have a Java server that does about 10-80 pushes/sec sustained (load varies by time of day) using pushy 0.14.1 on OpenJDK 8. We have configured the `ApnsClient` as follows:
```
            mApnsClient = new ApnsClientBuilder()
                    .setApnsServer(isProduction ? ApnsClientBuilder.PRODUCTION_APNS_HOST : ApnsClientBuilder.DEVELOPMENT_APNS_HOST)
                    .setSigningKey(new ApnsSigningKey(APNS_KEY_ID, APPLE_TEAM_ID, APNS_PRIVATE_KEY))
                    .setConcurrentConnections(CONCURRENT_CONNECTION_COUNT)
                    .setConnectionTimeout(Duration.ofSeconds(5))
                    .setMetricsListener(new ApnsClientMetricsListenerStatsD(statsDClient))
                    .build();
```
In the above code, `CONCURRENT_CONNECTION_COUNT` is 1.

We send push notifications as follows:
```
            mApnsClient.sendNotification(notification).whenComplete(mApnsListener);
```

We're seeing two kinds of problems with this server.

In the first problem, we see a bunch of write failures, and a connection removal, and maybe a connection addition (reported via the metrics listener, but unfortunately the last time it happened we just recorded these events via statsd, whereas now we are logging each event as it occurs, and will supply those details when we have them). However after these events indicating a connection problem with the APNS server, the `PushNotificationFuture`'s `whenComplete()` handlers stop being invoked, and things just stay stuck like that (no further connections added/removed or failed to create). We use a counting `Semaphore` to ensure we don't have more than 100 push notifications in flight at any time, so once the futures stop completing, we stop submitting new push notifications.

In the second problem, we see periods of as much as 10-30sec where no futures are completing, no connections are added/removed, no writes are failing, no connection attempts are failing (as reported by the metrics listener). In principle, this could just be a temporary network partition between us an the APNS server, or a period of (unexplained) slowness on the part of the APNS server. Normally we'd write the code in this case to have the push requests fail after some specified timeout (e.g. 5 seconds), and then close the connection on which the request timed out, and open a new one, but it's not clear to me how to do that with pushy.

Lawrence opened this issue because we were trying to debug through the pushy library itself to get more insight into what external conditions could lead to these observed states. We began by examining the stack trace in the exception passed in the `cause` argument of the `PushNotificationFuture`'s `accept()` method. As Lawrence points out, because of how the exception is allocated, it hides any information about where the failure was detected.

Perhaps you have a different suggestion of how to debug these kinds of problems?

Also, we notice that the library does not seem to have a notion of APNS request timeout. What do you think about having a way to have the `PushNotificationFuture` complete (exceptionally) if it does not finish within some time period? (JDK 9's `CompletableFuture` has an `orTimeout()` method but that's not available to us.)

Sorry for adding so much detail, but you are right to inquire about the underlying use case we're struggling with. Any help is appreciated!

**Comment by jchambers** [comment] 2020-09-19 14:36
Thanks—the detail is helpful, but there's a LOT going on here.

> In the first problem, we see a bunch of write failures…

Can you be more specific? Do your logs have a stack trace that lists a cause for the write failures?

> However after these events indicating a connection problem with the APNS server, the `PushNotificationFuture`'s `whenComplete()` handlers stop being invoked, and things just stay stuck like that…

That sounds like a serious bug. Understanding the events that lead up to that situation will be really important to solving this. I know that's exactly the point of this conversation, though.

> Perhaps you have a different suggestion of how to debug these kinds of problems?

I think the most helpful thing in this case would be to get some [frame logging](https://pushy-apns.org/apidocs/0.14/com/eatthepath/pushy/apns/ApnsClientBuilder.html#setFrameLogger(io.netty.handler.codec.http2.Http2FrameLogger)) in place. That will help us understand what the conversation between the client and server looks like prior to things going sideways.

> …because of how the exception is allocated, it hides any information about where the failure was detected.

This is true, but ultimately, knowing precisely where we detected that the channel closed doesn't actually provide meaningful debugging information. In all cases, all we'd know is that the channel closed before the push notification received a reply. That can happen at different points on the timeline, but the underlying phenomenon is still the same. None of the cases would tell us any more about _why_ the connection closed; we'd need to look elsewhere in the logs to find out more about that.

> What do you think about having a way to have the PushNotificationFuture complete (exceptionally) if it does not finish within some time period?

This has been discussed before. I'm generally not in favor of it because in virtually all cases, it's proposed as a workaround for some other issue, and I'd much rather fix the underlying issue.

So, for next steps, I think the right move is to get some frame logs to see if we can spot anything unusual in the conversation between the client and server. If you could share the cause of the write failures you're seeing (if not just "stream closed before a reply was received"), that'd be a big help, too.

I'll also take a look around and see if there are some opportunities to make logging a little more detailed.

**Comment by dcollens** [comment] 2020-09-21 16:00
> Can you be more specific? Do your logs have a stack trace that lists a cause for the write failures?

Yes, when I say a "bunch" of write failures, it was really just the same failure repeated 100 times (the max number of push requests we permit to be in flight). Here's the relevant log entry:
```
2020-09-05 21:07:47,783 WARN  None                   None                    - Exception communicating with APNs
java.io.IOException: Stream closed before a reply was received
        at com.eatthepath.pushy.apns.ApnsClientHandler.<clinit>(ApnsClientHandler.java:84)
        at com.eatthepath.pushy.apns.TokenAuthenticationApnsClientHandler$TokenAuthenticationApnsClientHandlerBuilder.build(TokenAuthenticationApnsClientHandler.java:88)
        at com.eatthepath.pushy.apns.TokenAuthenticationApnsClientHandler$TokenAuthenticationApnsClientHandlerBuilder.build(TokenAuthenticationApnsClientHandler.java:60)
        at io.netty.handler.codec.http2.AbstractHttp2ConnectionHandlerBuilder.buildFromCodec(AbstractHttp2ConnectionHandlerBuilder.java:551)
        at io.netty.handler.codec.http2.AbstractHttp2ConnectionHandlerBuilder.buildFromConnection(AbstractHttp2ConnectionHandlerBuilder.java:540)
        at io.netty.handler.codec.http2.AbstractHttp2ConnectionHandlerBuilder.build(AbstractHttp2ConnectionHandlerBuilder.java:504)
        at com.eatthepath.pushy.apns.ApnsClientHandler$ApnsClientHandlerBuilder.build(ApnsClientHandler.java:145)
        at com.eatthepath.pushy.apns.ApnsChannelFactory$1.initChannel(ApnsChannelFactory.java:128)
        at com.eatthepath.pushy.apns.ApnsChannelFactory$1.initChannel(ApnsChannelFactory.java:100)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:971)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:502)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:468)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:87)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:81)
        at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:323)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:155)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:116)
        at com.eatthepath.pushy.apns.ApnsChannelFactory.lambda$create$2(ApnsChannelFactory.java:176)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

> This is true, but ultimately, knowing precisely where we detected that the channel closed doesn't actually provide meaningful debugging information. In all cases, all we'd know is that the channel closed before the push notification received a reply. That can happen at different points on the timeline, but the underlying phenomenon is still the same. None of the cases would tell us any more about why the connection closed; we'd need to look elsewhere in the logs to find out more about that.

I agree, provided that there are no bugs in the pushy library. We were digging into the details to try to understand why and at what point pushy was concluding that the stream had closed, and whether this was in error, etc. I'm not suggesting we should continue down that path of debugging, but just explaining why we thought providing meaningful stack traces in pushy-generated exceptions would be valuable (i.e. when debugging the library itself).

Regarding timeouts for push requests, we had an incident yesterday where for about 45 seconds, almost no push requests completed (and a couple of 15s periods where 0 completed), and then they just suddenly started completing again. This time I can conclusively say that pushy did not report any write failures, connection removals/additions, etc. All the requests eventually completed normally. To me, this looks suspiciously like a network problem, or maybe a transient slowdown in the APNS server itself (although presumably if this were commonplace, we'd see more complaints of it?).

Now, I am not sure whether such a case argues for adding timeouts to requests or not: if it really is a transient network problem with the path to the APNS servers, what would you do with the timeout besides just retry anyway? If it's a slow APNS server endpoint, perhaps closing the connection to that endpoint, and reconnecting to a new one might help.

One experiment we thought we might try is to open 3-5 ApnsClient instances, each with a single connection, and then round-robin our requests across them, and wait for a similar problem to occur. Then we could determine whether all instances get stuck at the same time (suggesting a network problem) versus only one (which would be ambiguous, but might suggest a single APNS server was slow for some reason).

(As an aside, we don't know how to run that experiment with a single ApnsClient with multiple connections, because we don't know how to instrument which connection(s) are making progress and which ones are stuck, but let me know if you have any thoughts there.)

Do you think the experiment might be interesting, given that the most recent failure does not seem to implicate the pushy code itself?

We'll investigate the possibility of enabling frame logging.

**Comment by jchambers** [comment] 2020-09-26 15:47
> If it's a slow APNS server endpoint, perhaps closing the connection to that endpoint, and reconnecting to a new one might help.

Right—that's perhaps worth considering, but I think risks getting into some connection "flapping" situations that can look like a DoS attack if we're not careful. A challenge with timing out individual notifications is that the server sets a limit on the number of HTTP/2 "streams" we can have open at any given time. Even if we cancel the notification attempt on our side, the server still thinks that stream is active and won't release it for reuse. I guess that makes connection-level timeouts worth considering, but, again, those are a little scary.

> Do you think the experiment might be interesting, given that the most recent failure does not seem to implicate the pushy code itself?

Always good to have more data. At the very least, that can help us understand if the problem is some kind of bad network behavior or if there's something more subtle going on.

Overall, it sounds to me like this _is_ a case of choppy network conditions. More experiments—and especially some frame logs—will help us figure out if that's really the case and where to invest energy if so. Also: where are you servers located? Some regions—especially China—have notoriously bad connectivity to APNs servers.

Let's leave this issue open while we're gathering more information, but at this point, I don't think there's a bug in play.

**Comment by dcollens** [comment] 2020-09-28 19:01
> Overall, it sounds to me like this is a case of choppy network conditions. More experiments—and especially some frame logs—will help us figure out if that's really the case and where to invest energy if so. Also: where are you servers located? Some regions—especially China—have notoriously bad connectivity to APNs servers.

Our servers are located in Dallas, TX.

I don't have any frame logs for you yet, but I did have another occurrence where several in-flight push notification futures failed, immediately followed by pushy signalling a removed and added connection via the metrics listener.

The failures were a mixture of:

`java.io.IOException: Stream closed before a reply was received`

as I indicated up-thread, and some of these (haven't seen them before):
```
2020-09-22 17:34:07,461 WARN  None                   None                    - ApnsClient write failed (notificationId 10506001)
2020-09-22 17:34:07,463 WARN  None                   None                    - Exception communicating with APNs
io.netty.handler.codec.http2.Http2Exception$StreamException: Cannot create stream 21012007 greater than Last-Stream-ID 21011997 from GOAWAY.
        at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:147)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.checkNewStreamAllowed(DefaultHttp2Connection.java:874)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:748)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:668)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders0(DefaultHttp2ConnectionEncoder.java:201)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:167)
        at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:53)
        at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:53)
        at io.netty.handler.codec.http2.StreamBufferingEncoder.writeHeaders(StreamBufferingEncoder.java:153)
        at io.netty.handler.codec.http2.StreamBufferingEncoder.writeHeaders(StreamBufferingEncoder.java:141)
        at com.eatthepath.pushy.apns.ApnsClientHandler.writePushNotification(ApnsClientHandler.java:207)
        at com.eatthepath.pushy.apns.ApnsClientHandler.write(ApnsClientHandler.java:175)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
        at com.eatthepath.pushy.apns.ApnsClient.lambda$sendNotification$1(ApnsClient.java:205)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at com.eatthepath.pushy.apns.ApnsChannelPool.acquireWithinEventExecutor(ApnsChannelPool.java:172)
        at com.eatthepath.pushy.apns.ApnsChannelPool.lambda$acquire$0(ApnsChannelPool.java:126)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```
Is this exception also consistent with the server connection closing? Does it indicate an application-level GOAWAY frame from the APNS server on the other end of the connection, or could it also just mean that the connection closed/timed-out at the TCP level?

Separately from the above, on the evening of Sep 26 (about 2 days ago), my available Semaphore count started dwindling, suggesting that some push notification futures are never completing. This time instead of dropping precipitously, it has been leaking slowly for a couple of days, from 100 down to just over 40 at the moment. I realize that you've asked for frame logs during such an event, and I still have it on my list to set that up.

**Comment by jchambers** [comment] 2020-10-07 14:47
Folks, a quick update: it sounds like something changed upstream around September 19-21, which closely coincides with the release of iOS 14. Please see this mailing list thread for additional information: https://groups.google.com/g/pushy-apns/c/adcJ6ZjupYw/m/Yp3B95bRBgAJ

It sounds like the symptoms there are very similar to the ones described in this issue.

I hate to be a pest, but frame logging would be extraordinarily helpful in getting to the bottom of this.

**Comment by dcollens** [comment] 2020-10-07 16:00
Thanks, Jon, that thread is very interesting indeed. I agree the symptoms sound very similar.

Good news regarding frame logging. We did get it set up, and it has been running in our production environment for about 48 hours now (since Mon Oct 5). (It was easy to get working after we solved a serious misconfiguration in our logging, which was dropping all SLF4J-originating logs, but that took quite a bit of investigation.)

Since we started the server at Oct 5 18:00 UTC, we've lost about 50 of our 100 Semaphore permits (i.e. approximately 50 futures never completed). We have full frame logs for the entire period. Unfortunately, these logs total about 300MB gzipped.

I assume that what we'll find if we look at them is that there will be about 50 streamIds for which we see some OUTBOUND frames but then something anomalous in the response (maybe no response from the server, or maybe an unusual or unrecognized response). If it's as simple as a missing response, we could write a simple script to look for streamIds having OUTBOUND frames with no corresponding INBOUND frames. But that might turn up nothing if the response is there, but just in some unexpected format.

Do you want us to make the entire frame log available to you? Would that even be useful? Do you have some analysis tools you'd like us to run on the logs?

The best idea I have is for us to keep a HashSet of all in-flight push requests (add them as we push them into pushy, and remove them as the futures complete), and then every minute, log all the items from the set that have been in the set for more than a few minutes (they are probably stuck indefinitely by that point). That would let us know the precise time and push token for each future that failed to complete, and then we could pick out the precise set of frames from the log that relate to that push request. This is the approach I would plan to take unless you have a better/faster idea. I expect I could have that deployed within a day or two.

**Comment by gggsmith** [comment] 2020-10-08 04:12
Hi Jon,

We also experience very similar problem . Development of events in our case is the same as the way guys from referenced google groups thread described.
We also have been using pushy 0.13.10 and from the Sept 22 we had few incidents related to permits leakage.
We have multiple ios applications configured and the single event loop group for event processing (implemented with epoll).
In each incident permits leakage happened for only one ios application at the time (wich might be just a coincidence). 
During the incident we listened connections related to that ios application and they had some sort of traffing goung through (though cause it was crypted I cannot tell more about its nature, best guess is that it was ping frames). Heap dump inspection showed that lots of PushNotificationPromise were still alive. They were hold (transitively) by buffers of the io.netty.handler.codec.http2.StreamBufferingEncoder instances. Thought that we had been exceed the number of http2 streams per connection, but all the connections in the heap had no active streams. Decided that it might be some sort of bug in netty. We migrated to the version 0.14.1 yesterday (just one permit leaked since when).

**Comment by jchambers** [comment] 2020-10-08 23:31
Folks, we think we know what's going on: it looks like the APNs server just isn't sending responses to some notifications. If you'd be so kind, could you please share the UUID (`apns-id`) and approximate timestamp of at least one message that has timed out? Please let me know if you're not comfortable sharing that information in the open and we can work out a private communication channel.

Thank you!

**Comment by dcollens** [comment] 2020-10-09 01:25
Yes, we have several examples for you, Jon. We'd prefer to send them to you privately. We can DM you on Twitter to coordinate, if you like.

**Comment by jchambers** [comment] 2020-10-09 01:26
Sounds perfect. Thanks!

**Comment by lkesteloot** [comment] 2020-10-09 01:29
Hi Jon, looks like your DMs are closed. Can you DM me at @lkesteloot, my DMs should be open.

**Comment by jchambers** [comment] 2020-10-09 14:11
Folks, thanks for your ongoing help with this issue. Now that we know a more about what's going on and that we're pretty far away from the initial topic of this issue, I think it makes sense to consolidate discussion about this issue (which is currently happening across a number of different issues/threads) into one ticket.

I'm going to close this in favor of #816; let's continue the conversation there. Thanks very much!

**Closed by jchambers** 2020-10-09 14:11 UTC
