### ISSUE TITLE
Question about response from APNs

### ISSUE THREAD

**Issue by leiwei999** [jchambers/pushy#818] opened 2020-10-19 10:50 UTC
An example:

```
Semaphore semaphore = new Semaphore(1000); foreach(Object pushNotification : list) {
	semaphore.acquire();
	final Future<PushNotificationResponse<SimpleApnsPushNotification>> future = apnsClient.sendNotification(pushNotification);
	future.addListener(new GenericFutureListener<Future<PushNotificationResponse<SimpleApnsPushNotification>>>() {
	 	 @Override
	     public void operationComplete(Future<PushNotificationResponse<SimpleApnsPushNotification>> pushNotificationResponseFuture) throws Exception {
	       // TODO
	       
	       semaphore.release();
	     }
	 
	}
}

```
the above processing, is it possible that the number of messages sent and received is different(sendNotification number ≠ operationComplete number)，
When does this happen? Does it happen if some thread is blocked?

Looking forward to your answers.
Best regards.

**Comment by jchambers** [comment] 2020-10-19 14:01
This appears to be a duplicate of #816. Let's continue the discussion there.

**Closed by jchambers** 2020-10-19 14:01 UTC
Labels: duplicate
