### ISSUE TITLE
Failed to create channel : io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: TLSv1.3

### ISSUE THREAD

**Issue by sarika3333** [jchambers/pushy#875] opened 2021-04-03 15:20 UTC
netty 4.1.63, netty-tcnative-boringssl-static-2.0.38.Final.jar,  pushy to 0.14.2, JDK : 1.8 , supported protocol:  TLSv1, TLSv1.1,TLSv1.2. 

Error:
 com.eatthepath.pushy.apns.ApnsChannelPool lambda$acquireWithinEventExecutor$2
WARNING: Failed to create channel
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: TLSv1.3
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:478)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: TLSv1.3
        at com.ibm.jsse2.U.a(U.java:55)
        at com.ibm.jsse2.az.a(az.java:73)
        at com.ibm.jsse2.az.chooseEngineClientAlias(az.java:38)
        at io.netty.handler.ssl.OpenSslKeyMaterialManager.chooseClientAlias(OpenSslKeyMaterialManager.java:126)
        at io.netty.handler.ssl.OpenSslKeyMaterialManager.setKeyMaterialClientSide(OpenSslKeyMaterialManager.java:95)
        at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$OpenSslClientCertificateCallback.handle(ReferenceCountedOpenSslClientContext.java:266)
        at io.netty.internal.tcnative.SSL.readFromSSL(Native Method)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:634)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1258)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1384)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1427)
        at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:208)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1358)
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1265)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1302)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
        ... 17 more

**Comment by jchambers** [comment] 2021-04-03 16:46
This appears to be a duplicate of #864. Let's consolidate things there.

**Closed by jchambers** 2021-04-03 16:46 UTC
