### ISSUE TITLE
A null response problem

### ISSUE THREAD

**Issue by Sycamore-M** [jchambers/pushy#778] opened 2020-05-07 07:31 UTC
Sometimes I get a null response when calling future.getNow().
What can cause this problem?
Should I retry or ignore it?

**Comment by jchambers** [comment] 2020-05-07 13:14
This sounds like a duplicate of #767. We've already merged a fix and will have a new release out shortly.

**Closed by jchambers** 2020-05-07 13:14 UTC

**Comment by Sycamore-M** [comment] 2020-05-07 14:23
> This sounds like a duplicate of #767. We've already merged a fix and will have a new release out shortly.
I am not sure if it's duplicate, because no exception was thrown.
Here is my code:
![image](https://user-images.githubusercontent.com/64950896/81304980-5c92f480-90b0-11ea-9752-6cbb440f85e5.png)
I can wait for the new release and see if it works.
Thanks!
