### ISSUE TITLE
duplicated notification maybe caused by retry

### ISSUE THREAD

**Issue by cyflhn** [jchambers/pushy#794] opened 2020-07-13 05:39 UTC
We have found that occasionally the device received duplicated notifications while we only sent once. I have checked the source code of pushy and found that pushy will resend the notification if RST_STREAM is received and the error code is REFUSED_STREAM.
But I also check the issue of #476, the trace log shows that for the same stream id 25, both error code 7 and 5 are received. According to the handling of retry in pushy, is it possible that the retry could cause the deplicated notification?
By the way, I still don't understand why both error code 7 and 5 could be received for the same stream id.

**Comment by jchambers** [comment] 2020-07-18 14:44
> According to the handling of retry in pushy, is it possible that the retry could cause the deplicated notification? …By the way, I still don't understand why both error code 7 and 5 could be received for the same stream id.

No, and this is addressed specifically in the [comments](https://github.com/jchambers/pushy/pull/486/files#diff-8878dfd46233d570d7aab988b99e41fbR348-R351) for #486, which fixed #476:

> This can happen if the server reduces MAX_CONCURRENT_STREAMS while we already have notifications in flight. We may get multiple RST_STREAM frames per stream since we send multiple frames (HEADERS and DATA) for each push notification, but we should only get one REFUSED_STREAM error; the rest should all be STREAM_CLOSED.

I don't think the logic introduced in #486 is likely to be the cause of what you're seeing, but I can't rule it out, either. It may be that it's not a bug in Pushy at all, but something that's happening upstream (e.g. the server _says_ it rejected the stream, but somehow processed it anyhow). To narrow it down, we'll need more information. You could try enabling `trace` logging for `ApnsClientHandler` to see if you can spot evidence of the same push notification getting written twice. You could also consider adding logging to the receiving app somehow to see if the duplicate notifications have the same UUID.

Either way, I don't think we can make much progress on the issue without a more specific problem statement.

**Comment by cyflhn** [comment] 2020-07-19 08:52
> You could also consider adding logging to the receiving app somehow to see if the duplicate notifications have the same UUID
According to my colleagues, if two notifications has the same UUID, the second one won't be showed on the device. UUID has  similar function of collapse id.

**Comment by jchambers** [comment] 2020-07-19 14:37
Okay; and are you assigning your own UUIDs or letting the server do that? As an experiment (and if you're not already doing it), it might help narrow the problem space a bit if you provide your own UUIDs. If that resolves the problem, it'll give us some helpful hints about where things might be going wrong.

**Comment by jchambers** [comment] 2020-08-23 17:18
I'm going to close this issue for now because we don't really have enough information to take any kind of action. @cyflhn if you get a chance to provide more information, please post a comment here and I'll happily re-open the issue. Thanks!

**Closed by jchambers** 2020-08-23 17:18 UTC
