### ISSUE TITLE
Intermittent layer 7 firewall blocks due to missing SNI

### ISSUE THREAD

**Issue by danwashusen** [jchambers/pushy#1002] opened 2022-12-20 00:23 UTC
Hi and thanks for your work on Pushy!

We are seeing occasional/intermittent network firewall blocks (AWS Network Firewall) for request that are originating from the Pushy lib. The requests in question are attempting to connect to port 443 on a specific (Apple) IP address, without the SNI hostname which means they don't match the `api.push.apple.com` hostname mentioned in the firewall allow-list.

Looking through the code I can't really see any reason why only *some* requests would not comply with SNI, however I notice that Pushy isn't specifically using the `io.netty.handler.ssl.SniHandler` (https://netty.io/4.1/api/io/netty/handler/ssl/SniHandler.html). So the fix may be as easy as specifically enabling SNI in Netty code...

Not sure if it makes a difference but we are using the JDK impl. of the SSL provider.

**Comment by jchambers** [comment] 2023-01-01 16:19
Please pardon the slow reply.

That's… exceptionally strange. I've never seen that happen in the wild, and so don't really have a great way to reproduce the issue. Are you in a position to try the `SniHandler` approach on your end and see if it resolves the problem?

**Comment by jchambers** [comment] 2023-08-04 00:59
I'm going to close this issue because it does not appear to be widespread and I can't reproduce it locally, and so I don't have any way of knowing whether any change I could make has actually addressed the problem.

@danwashusen if you're in a position to provide more information, please leave a comment here and I'll happily reopen the issue!

**Closed by jchambers** 2023-08-04 00:59 UTC
